services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend:/app
    dns:
      - 8.8.8.8
      - 1.1.1.1
    command: sh -c "python manage.py migrate && daphne -b 0.0.0.0 -p 8000 config.asgi:application & python bot/bot.py"

  frontend:
    build:
      context: ./frontend/react-chat-cra
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: npm start

  redis:
    image: redis:7


  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  postgres_data:

