# Generated by Django 5.2.4 on 2025-07-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_auth', '0003_alter_room_check_in_alter_room_check_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_active',
        ),
        migrations.AddField(
            model_name='room',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
