# Generated by Django 5.2.4 on 2025-07-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_auth', '0004_remove_room_check_in_remove_room_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
