# Generated by Django 5.2.4 on 2025-07-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_auth', '0005_alter_room_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='qr_code',
            field=models.CharField(default='2cc0b7e39afe4336944167505110524b', max_length=32, unique=True),
        ),
    ]
