# Generated by Django 5.2.4 on 2025-07-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_auth', '0006_room_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='qr_code',
            field=models.CharField(default='e03e7c1ab91a4d54ba41a489734014c9', max_length=32, unique=True),
        ),
    ]
