# Generated by Django 5.2.4 on 2025-07-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_auth', '0007_room_language_alter_room_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='qr_code',
            field=models.CharField(default='7702c88f301d4e4c98edbeb4aaf34234', max_length=32, unique=True),
        ),
    ]
